export './pages/landing.dart';
export './pages/login.dart';
export './pages/signup.dart';
export './pages/forget_password.dart';
export './pages/reset_password.dart';
export './pages/home.dart';
export './pages/reminder.dart';
export './pages/add-reminder.dart';
export './pages/notes.dart';
